### ISSUE TITLE
Not working in google colab

### ISSUE THREAD

**Issue by githubtrip** [sandeepyadav1478/Uploading-video-on-youtube#2]
Nice concept.

However, not working in google colab. Seems socket error

`    464         if self.allow_reuse_address:
    465             self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
--> 466         self.socket.bind(self.server_address)
    467         self.server_address = self.socket.getsockname()
    468 

OSError: [Errno 98] Address already in use`

**Comment by sandeepyadav1478** [comment]
Ahh! I think it may occur due to YouTube v3 api verification. have u verified the link, given in description? as ''www.youtube.com/verify"

**Comment by sandeepyadav1478** [comment]
Coz I tested this code around 18-20 days ago. At that time it was running successfully.

**Comment by sandeepyadav1478** [comment]
### **Please complete all procedure bulletin points before executing the code.**

**Comment by githubtrip** [comment]
Managed to solve. Thank you
